# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Baobaohuang
tagline:             The Jekyll Butler
url:                 http://baobaohuang.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Baobaohuang
  url:               https://twitter.com/Baobaohuang
  email:             Baobaohuang@gmail.com

# Navigation bar  
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
  Bookmark:'/bookmarks'

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/baobaohuang/baobaohuang.github.io
